### PR TITLE
Also compile with clang in CI

### PR DESCRIPTION
**Pull request by qbarrand**

### CODE REVIEW

**Comment by XVilka** [comment]
Can you setup `CC=gcc` for AppVeyor too while you are on it?

**Comment by XVilka** [comment]
In fact maybe caching or something can improve the AppVeyor speed. choko is quite slow. See also https://github.com/appveyor/ci/issues/3009 and https://github.com/appveyor/ci/issues/3058

**Comment by XVilka** [comment]
See the choko caching for AppVeyor https://www.appveyor.com/docs/build-cache/

**Comment by qbarrand** [comment]
Will cache choco packages using
```yaml
cache:
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
```
However the build time itself is already rather short, the problem is that jobs are queued for ages :disappointed:

**Comment by XVilka** [comment]
@qbarrand actually we can try to setup Azure Pipelines. They are damn fast:
- https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/go?view=azure-devops
- https://medium.com/@tsuyoshiushio/azure-devops-yaml-pipeline-with-coverage-report-for-go-lang-fd2163b3d254

**Comment by qbarrand** [comment]
There's also Travis, although windows builds are rather slow and I somehow cannot make the matrix work.

**Comment by XVilka** [comment]
You can add Azure Pipelines YAML file, I enabled it for the repository

**Comment by qbarrand** [comment]
@XVilka Do we really want yet another CI? It works in Travis for Windows + gcc https://travis-ci.org/radareorg/r2pm/jobs/575841184

**Comment by qbarrand** [comment]
@XVilka Could we remove `.builds/openbsd.yml`? I think it's the only CI that fails now.

**Comment by XVilka** [comment]
Azure is faster, so we eventually can add installability checks and more tests.
For the OpenBSD - let it fail for now, we'll see if it's possible to fix somehow, maybe complain to Go or OpenBSD developers

**Comment by XVilka** [comment]
Seems AppVeyor clang build also failing by the way

**Pull request merged**
